Use func location to grab source code
ThinkOpenly/sail pull request #12
Opened 2024-03-28 05:57 UTC by rod7760

Fixes #3 

## Design
 `sail_doc_backend` (seems to be used by `asciidoctor-sail`) grabs the source code to create the "Documentation Bundle" (`doc.json.`) I just stole some of that code.
 
## Create an example documentation bundle
If you are curious about the documentation bundle format. You can generate one:
```
make -C doc/asciidoc/
vim doc/asciidoc/sail_doc/exn.json
```

## Result
```
{
  "mnemonic": "addiw",
  "name": "Add Immediate Word",
  "operands": [
{
  "name": "imm", "type": "bits(12)"
}, 
{
  "name": "rs1", "type": "regidx"
}, 
{
  "name": "rd", "type": "regidx"
} ],
  "format": "I",
  "fields": [ { "field": "imm", "size": 12 }, { "field": "rs1", "size": 5 }, { "field": "0b000", "size": 3 }, { "field": "rd", "size": 5 },>
  "extensions": [  ],
  "function": "{\n  let result : xlenbits = sign_extend(imm) + X(rs1);\n  X(rd) = sign_extend(result[31..0]);\n  RETIRE_SUCCESS\n}",
  "description": "\nThe ADDIW instruction involves adding a sign-extended\n12-bit immediate value to the content of register rs1. The resul>
},
```

2024-03-28 06:03 UTC, rod7760 commented
Please let me know how I can clean this up. The code was grabbed from `src/sail_doc_backend/docinfo.ml`, but maybe we can place it in a utility file (Ast_util.ml?). That way several backends can use it.

2024-03-28 18:18 UTC, ThinkOpenly commented
> Please let me know how I can clean this up. The code was grabbed from `src/sail_doc_backend/docinfo.ml`, but maybe we can place it in a utility file (Ast_util.ml?). That way several backends can use it.

This is fantastic! Great work.

I concur with your idea to move it into a commonly useful area. Since the new code doesn't really work with an AST, I wonder if somewhere in Libsail would be a better home. I haven't looked too deeply, but I do see a `read_source` function there (`src/lib/chunk_ast.ml`), which is vaguely similar, but definitely different. I didn't look exhaustively, but I didn't find a perfect location. Perhaps `src/lib/util.ml`.

If you take this on, consider porting `src/sail_doc_backend/docinfo.ml` to use the new location, and submitted those changes to the upstream Sail repository.

The original changes suggested here are certainly good enough as-is, but let me know how you'd like to proceed. (Moving into Libsail could be a follow-up change, and porting the "doc" backend to use that could a follow-up to that. And, I'm not necessarily expecting you to do any of the follow-up work. We can open issues to keep track.)

2024-03-28 19:02 UTC, rod7760 commented
Great! I can open a PR upstream for moving the utility function into Libsail. I'll send a link to that PR later. We can rebase whenever that gets merged in. Thanks.

2024-03-28 19:47 UTC, rod7760 commented
Ah. The upstream does have this function now.

https://github.com/rems-project/sail/blob/sail2/src/lib/util.ml#L367

If we sync the fork and rebase, I can use it.

2024-03-29 00:05 UTC, rod7760 commented
Upstream pr is [here](https://github.com/rems-project/sail/pull/482)

2024-03-29 01:45 UTC, ThinkOpenly commented
> Upstream pr is [here](https://github.com/rems-project/sail/pull/482)

And, it's already merged! Nice! and nice work!

I'll start on rebasing the "json" branch here.

2024-03-29 19:42 UTC, rod7760 commented
This should be ready for final review.

2024-03-29 22:10 UTC, ThinkOpenly requested changes
Functionally, this really turned out neat and very useful.

For the benefit of those coming along in the future, could you expand the commit message just a bit? Perhaps something like:
--
Subject: [JSON] Extract function body verbatim from Sail source

Use the newly available `Reporting.loc_range_to_src` function
to extract the text of the function bodies verbatim from the
Sail source, avoiding the mangled text that appears in the AST.
--
... or something like that.

That gives the subject more human readability, describes the problem, and the solution provided by your change.

2024-03-29 23:01 UTC, rod7760 commented
Updated the commit message. Thanks!

2024-03-29 23:22 UTC, merged