Extracting Depedent functions
ThinkOpenly/sail pull request #20
Opened 2024-05-22 12:49 UTC by snapdgn

Fixes: https://github.com/ThinkOpenly/sail-riscv/issues/17
This currently extracts the dependent function(not exactly: it extracts **all** the `function` defs)  into a new hashtable.

2024-05-23 17:00 UTC, ThinkOpenly requested changes
Nice work! I have a couple of minor comments inline.

2024-05-23 17:00 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +            let operandl = List.concat (List.map string_list_of_pat pl) in
I don't think this line is needed. `operandl` is not used in the subsequent code in this stanza.

2024-05-23 17:00 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +  print_endline "  \"dependent_functions\": [";
Since the set of functions here are not all dependencies, let's change the key here to something more generic like "functions" (in some ways, these are "independent functions", but I think "functions" is nicely generic).

2024-05-23 17:21 UTC, snapdgn commented on src/sail_json_backend/json.ml
> +  print_endline "  \"dependent_functions\": [";
what about the hashtable name for it, should i rename that too? That would conflict with the already defined 'functions' table(which hosts the 'function clause execute'). Should that be renamed to something else too?

2024-05-23 17:27 UTC, snapdgn commented on src/sail_json_backend/json.ml
> +            let operandl = List.concat (List.map string_list_of_pat pl) in
Yeah, sorry totally missed it.

2024-05-23 17:37 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +  print_endline "  \"dependent_functions\": [";
> That would conflict with the already defined 'functions' table
I certainly overlooked that. I'm really tempted to rename the older table from "functions" to, say, "executes" (not terribly excited by that name, though).

If you are willing, could you create a first patch which does that rename, then add your changes as separate patch(es) on top of that?

2024-05-24 15:13 UTC, snapdgn commented on src/sail_json_backend/json.ml
> +  print_endline "  \"dependent_functions\": [";
Just to make sure i understand correctly, I should just rename `  print_endline "  \"dependent_functions\": [";
` at first. And then work on renaming things like prior `functions` fields to let's say `execute` etc..?

2024-05-24 15:26 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +  print_endline "  \"dependent_functions\": [";
Sorry for the confusion. I suggest creating a "first patch" which renames the existing "functions" `Hashtbl` to something more apt, like "executes", or "semantics", or "rtl". (As you can see, I'm having trouble coming up with a perfect name.)

Then, you can have a second patch (or more, if needed) that adds your new "functions" `Hashtbl` that collects _all_ of the other function bodies (without a name collision on "functions").

2024-05-24 15:31 UTC, snapdgn commented on src/sail_json_backend/json.ml
> +  print_endline "  \"dependent_functions\": [";
got it, thanks for the clarification.

2024-05-24 16:22 UTC, snapdgn commented
Let me know if this looks any good. @ThinkOpenly

2024-05-24 17:48 UTC, ThinkOpenly commented
> Let me know if this looks any good.

I like that there is a single commit that renames "functions" to "executes". Are you planning to squash together the rest of the patches? I was expecting the final set of commits to look something like:
1. rename "functions" to "executes"
2. extract function bodies to new Hashtbl "functions"

2024-05-30 04:30 UTC, snapdgn commented
Apologies for the delay, it slipped my mind entirely.
I couldn't squash it into two commits because i couldn't directly create a hashtable named `functions` (since it was already taken). 
Let me know if the above seems good.

2024-05-30 20:36 UTC, ThinkOpenly commented
> Apologies for the delay, it slipped my mind entirely. I couldn't squash it into two commits because i couldn't directly create a hashtable named `functions` (since it was already taken). I've squashed some of previous ones though. Let me know if the above seems good.

Here's what I was thinking. You currently have 4 commits:
1. [JSON]: Implement support for optional operand
   _Actually, should this be here? I think you need to rebase._
1. [JSON]: extract function bodies to a new hashtable `depedendent_functions`
1. rename `functions` to `executes`
1. rename `dependent_functions` to `functions`

I propose rebasing/reordering/squashing to produce 2 commits:
1. rename `functions` to `executes`
1. squash the following into a single commit:
   1. extract function bodies to a new hashtable
   1. rename `dependent_functions` to `functions`

2024-05-31 13:16 UTC, snapdgn commented
- rebased against upstream.
- reordered & squashed as suggested.

2024-05-31 13:47 UTC, ThinkOpenly approved these changes

2024-05-31 13:47 UTC, merged