Remove macos12 4.08.1 build
ThinkOpenly/sail pull request #37
Opened 2024-08-09 04:10 UTC by joydeep049

PR based on discussion [here](https://github.com/ThinkOpenly/sail/pull/35#issuecomment-2274264247)

cc @ThinkOpenly

2024-08-09 17:05 UTC, ThinkOpenly requested changes
For commits, in most cases, I prefer to have some relevant content in the commit message, unless the subject line covers it all. Here, the subject line explains the change, but not the motivation behind it.

Please add content that describes the issue, the cause of the issue, and how the fix addresses the issue. Something like:
> GitHub CI "build" Action often (always?) fails on target "macos-12" with errors like:
> ```
> # File "src/sail_json_backend/json.ml", line 97, characters 5-23:
> # 97 |   if String.starts_with ~prefix:"\"" qs && String.ends_with ~suffix:"\"" qs then
> #           ^^^^^^^^^^^^^^^^^^
> # Error: Unbound value String.starts_with
> ```
> This error message is indicative of an outdated version of OCaml. Support in OCaml for `String.starts_with` arrived in OCaml 4.13, which was released almost 2 years ago (2021-09-24). This issue occurs on the "macos-12" target exclusively.
> Since the work being done here is not platform-specific and is at the level of "proof-of-concept", disable the "macos-12" platform and move on.

... or something like that.

2024-08-11 06:14 UTC, joydeep049 commented
I've changed the description message. Hope that works.

2024-08-12 21:15 UTC, ThinkOpenly commented
What you did:
> I've changed the description message. Hope that works.

What I asked:
> I prefer to have some relevant content in the commit message

:-)

Could you add that text in the commit message, rather than in the PR description? The commit message stays with the repository even when somebody clones it, so they can see what was done, why, and by whom when executing simple commands like `git log`, `git show`, etc.

2024-08-12 21:50 UTC, joydeep049 commented
My apologies for not being able to follow before. 
 I hope this works.
 @ThinkOpenly

2024-08-14 21:15 UTC, ThinkOpenly commented
I'm sorry to be a pain on this small change, but that's a mentor's job, I guess. Here's the commit message I see when I clone your GitHub branch:
```
    Remove macos-12 4.08.1 build
     === ERROR while compiling sail_json_backend.0.17 =============================
     File "src/sail_json_backend/json.ml", line 97, characters 5-23:
     97 |   if String.starts_with ~prefix:"\"" qs && String.ends_with ~suffix:"\"" qs then
               ^^^^^^^^^^^^^^^^^^
     Error: Unbound value String.starts_with
    
      - This error message is indicative of an outdated version of OCaml.
      - This issue occurs on the "macos-12" target exclusively.
      - Since the work being done here is not platform-specific, disable the macos-12 platform.
```

Suggestions:
- Put a blank line after the subject (first) line.
- Put some introduction/context before the error message text, as I suggested previously, that indicates that this error message is appearing in the results of a CI Action.
- Quote the error message text between lines starting with triple-backquotes, like:
  ```
  this
  ```
  If you don't favor the Markdown-style triple-backquotes, some innocuous separator is helpful, like "--" before and after. (The markdown style leads to better display on GitHub.)
- Maybe include some of the context that I suggested previously, like:
  - Support in OCaml for String.starts_with arrived in OCaml 4.13
  - OCaml 4.13 was released almost 2 years ago (2021-09-24)
  These facts convey that we're not just ignoring a valid error, but utilizing features that have been supported for some time.

2024-08-15 08:12 UTC, joydeep049 commented
The markdown style triple-backquotes do not seem to work on a commit message. Am I doing anything wrong here?

2024-08-15 19:03 UTC, ThinkOpenly approved these changes

2024-08-15 19:06 UTC, merged