Fixed find_extensions to look for new Sail extension format
ThinkOpenly/sail pull request #42
Opened 2024-09-30 01:23 UTC by BrianAnakPintar

Updated the `find_extensions` function to support the new syntax for extension parsing.
- **Previous Format**: `extension("Zba")`
- **New Format**: `extensionEnabled(Ext_Zba)`

2024-10-03 14:01 UTC, ThinkOpenly requested changes
Nice! I have 2 minor comments about comments only.

2024-10-03 14:01 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +(* This looks for any "extensionEnabled(string)", and does not, for example
The "string" in this line should probable be changed to "enum", just to be clear that we're not expecting a string literal, but an identifier.

2024-10-03 14:01 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +          "\"" ^ String.sub ext_str 4 (String.length ext_str - 4) ^ "\""
Could you add a comment above this line explaining that the magic numbers "4" are being used to remove the "Ext_" prefix from the extension enum identifier? Even something simple like:
```
(* Remove "Ext_" prefix from extension enum. *)
```

2024-10-07 14:31 UTC, ThinkOpenly requested changes
Looks like a couple of unrelated changes leaked in?
Also, a small change requested...

2024-10-07 14:31 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +    | FCL_aux (FCL_funcl (Id_aux (Id id, _), Pat_aux (pat, _)), _) -> begin
Did you intend to include these changes? They don't seem material to this PR.

2024-10-07 14:31 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +    | _ -> debug_print "FCL_funcl other"
Did you intend to include this change? They don't seem material to this PR.

2024-10-07 14:31 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +      (* If it's extensionEnabled, we remove the Ext_ prefix (4 characters) *)
Since this PR needs changes anyway, could you add quotes around "Ext_"?
And, let's move this comment to just above the `String.sub` line, maybe something like:
```
(* extensionEnabled enums are expected to be of the form "Ext_" + extension short name.
   Remove the "Ext_" prefix and keep just the extension short name. *)
```

2024-10-07 14:47 UTC, BrianAnakPintar commented on src/sail_json_backend/json.ml
> +      (* If it's extensionEnabled, we remove the Ext_ prefix (4 characters) *)
Whoopsies, I'll get that fixed at the end of the day.

2024-10-14 19:51 UTC, ThinkOpenly commented
A few more comments... I just noted that your commit message uses past tense ("Fixed ..."). Imperative tense is preferred ("Fix ...").

You could also shorten it a bit, at your option:
"Adapt to new extensionEnabled syntax".

Oh, may I also ask you to prefix your commit messages with the backend name ("[JSON]")?

In summary, "[JSON] Adapt to new extensionEnabled syntax".

2024-10-15 15:23 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +    | FCL_aux (FCL_funcl (Id_aux (Id id, _), Pat_aux (pat, _)), _) -> begin
Still a couple of innocuous indentation changes that snuck in. Could you revert the extra spaces added for these two lines?

2024-10-23 05:06 UTC, ThinkOpenly approved these changes

2024-10-23 05:26 UTC, ThinkOpenly commented
The CI didn't like your formatting.
Could you run `dune fmt` on your changes, and push another commit with those changes?

2025-02-01 16:42 UTC, merged