Working Format Mapping
ThinkOpenly/sail pull request #43
Opened 2024-10-27 20:14 UTC by WayfaringKid

1. Added a new hash table `instruction_type_to_format`.
2. Updated `parse_mapcl` function to handle format mapping. Add `handle_fmtencdec_mapping` to map instruction type to corresponding format. Two mapping doesn't work with this version: mnemonic "illegal" and "c.illegal". 
4. Updated `parse_funcl` function to have debug statement for each pattern.

2024-10-31 20:09 UTC, ThinkOpenly requested changes
A few general themes:
- split debugging-only changes into a separate, initial commit (make reviewing substantive changes easier)
- avoid unnecessary whitespace changes (same)
- consider whether comments are helpful in understanding the code

Separately, these changes failed to compile for me:
```
File "src/sail_json_backend/json.ml", line 470, characters 8-12:
470 |         else
              ^^^^
Error: Syntax error: 'end' expected
File "src/sail_json_backend/json.ml", line 456, characters 68-73:
456 |   | FCL_aux (FCL_funcl (Id_aux (Id id, _), Pat_aux (pat, _)), _) -> begin
                                                                          ^^^^^
  This 'begin' might be unmatched
```
Do you not see these errors? Always, always make sure your code compiles, runs, and produces the results you expect.

Lastly, I always suggest making changes in a new branch. This makes code management a bit easier for you.

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +
Extraneous whitespace added here. Could you remove these two blank lines?
PRs should just have material changes. (If there are necessary whitespace changes, they should be in a separate commit.)

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +  let handle_fmtencdec_mapping mc =
I'm not a fan of large in-line functions within other functions. I find it more difficult to understand. Could you make `handle_fmtencdec_mapping` a top-level, standalone function, please?

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +          | _ -> debug_print "Unhandled pattern in fmtencdec mapping"
should this be an `assert`, or is this a "don't care" case?

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +          List.iter (fun s -> debug_print ("R: " ^ s)) sl_right;
In order to make reviews easier, it is helpful to separate changes into separate commits that, for example, only add debugging statements, and other commits that make material changes. In this code, the changes that modify "encdec" and "assembly" stanzas (and below) could come as a first commit, and the changes that implement support for "fmtencdec" could come as a second commit.

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +*)
I think you can remove this comment.

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +          debug_print ("parse_funcl id_of_dependent: " ^ id);
a debug change that would go in a first commit.

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +          debug_print ("parse_funcl FCL_funcl execute " ^ id);
a debug change that would go in a first commit.

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +        (* This mapping is kinda unnecessary, depend on future tasks *)
remove

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +      | _ -> debug_print ("Other pattern in " ^ id)
a debug change that would go in a first commit.

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +
remove

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +
remove

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +  (* Debug message to print the value of k *)
remove

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +  debug_print ("K is " ^ k);
a debug change that would go in a first commit.

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +
remove

2024-10-31 20:09 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +
remove

2024-11-05 03:50 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +
Addressed

2024-11-05 03:50 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +  let handle_fmtencdec_mapping mc =
Addressed

2024-11-05 03:51 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +          | _ -> debug_print "Unhandled pattern in fmtencdec mapping"
This is a don't care case, changed to `| _ -> ()`

2024-11-05 03:51 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +          List.iter (fun s -> debug_print ("R: " ^ s)) sl_right;
Addressed. Seperated into commit `functional change` and `debugging m
essages, fmtencdec not mapped`

2024-11-05 03:51 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +*)
Addressed

2024-11-05 03:52 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +
Addressed

2024-11-05 03:52 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +
Addressed

2024-11-05 03:52 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +  debug_print ("K is " ^ k);
Addressed

2024-11-05 03:52 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +  (* Debug message to print the value of k *)
Addressed

2024-11-05 03:53 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +
Addressed

2024-11-05 03:53 UTC, WayfaringKid commented on src/sail_json_backend/json.ml
> +
Addressed

2024-11-05 17:03 UTC, ThinkOpenly requested changes
Still a few minor comments, inline.

Also, could you restructure your commits to just two:
1. one with new debugging statements only
1. one with functional changes

2024-11-05 17:03 UTC, ThinkOpenly commented on ISA.json
Remove this file, please.

2024-11-05 17:03 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +              annot.attrs
I see these two lines only have blank space changes. Unless `dune fmt` added these, could you revert these changes?

2024-11-05 17:03 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +    handle_fmtencdec_mapping mc;
Could you make this indentation match the indentation of similar stanzas, below?

2024-11-05 17:03 UTC, ThinkOpenly commented on src/sail_json_backend/json.ml
> +
remove this added line, please.

2024-11-29 14:44 UTC, ThinkOpenly commented
The current changes look pretty good, although I only did a quick review. Can you describe the effect of applying these changes on the resulting JSON?

2024-11-29 17:12 UTC, WayfaringKid commented
When running our parser upstream-formats branch, it parse the formats for each instructions.
For example, this is the output of add:
`{
  "mnemonic": "add",
  "name": "TBD",
  "operands": [ { "name": "rd", "type": "regidx", "optional": false },{ "name": "rs1", "type": "regidx", "optional": false },{ "name": "rs2", "type": "regidx", "optional": false } ],
  "syntax": "rd,rs1,rs2",
  "format": "RFormat",
  "fields": [  ],
  "extensions": [  ],
  "function": "{\n  let rs1_val = X(rs1);\n  let rs2_val = X(rs2);\n  let result : xlenbits = match op {\n    RISCV_ADD  => rs1_val + rs2_val,\n    RISCV_SLT  => zero_extend(bool_to_bits(rs1_val <_s rs2_val)),\n    RISCV_SLTU => zero_extend(bool_to_bits(rs1_val <_u rs2_val)),\n    RISCV_AND  => rs1_val & rs2_val,\n    RISCV_OR   => rs1_val | rs2_val,\n    RISCV_XOR  => rs1_val ^ rs2_val,\n    RISCV_SLL  => if   sizeof(xlen) == 32\n                  then rs1_val << (rs2_val[4..0])\n                  else rs1_val << (rs2_val[5..0]),\n    RISCV_SRL  => if   sizeof(xlen) == 32\n                  then rs1_val >> (rs2_val[4..0])\n                  else rs1_val >> (rs2_val[5..0]),\n    RISCV_SUB  => rs1_val - rs2_val,\n    RISCV_SRA  => if   sizeof(xlen) == 32\n                  then shift_right_arith32(rs1_val, rs2_val[4..0])\n                  else shift_right_arith64(rs1_val, rs2_val[5..0])\n  };\n  X(rd) = result;\n  RETIRE_SUCCESS\n}",
  "description": "TBD"
},`

We can see that RFormat is parsed for add.

2025-02-01 18:59 UTC, ThinkOpenly commented
I squashed and merged this via #48

2025-02-01 18:59 UTC, closed without merging